### ISSUE TITLE
Links Not opening in Private Windows

### ISSUE THREAD

**Issue by RuthlessRuler** [LinkSheet/LinkSheet#462] opened 2024-10-13 12:40 UTC
### Bug description

If Don't show "last picked app" is disabled and a link is opened that had suggestions for last picked app like Firefox, then despite clicking on Private Windows Icon to open the link in Private tab, the Link ends up opening in normal tab.

### Experiments

- [X] I have disabled all experiments

### Version

master-4678cba-nightly

### Device

Poco X3 Pro

### Android version

Android 14 (Stock)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment] 2024-10-15 03:59
I'm not quite sure I understand correctly as I can't reproduce this - would you mind sharing a screen recording?

**Comment by 1fexd** [comment] 2024-10-15 04:42
Should be fixed when the `improved_intent_resolver` experiment is enabled - does that work for you?

**Comment by RuthlessRuler** [comment] 2024-10-15 12:01
I hope this explains it better.
https://github.com/user-attachments/assets/159df2e1-98bb-4331-bf51-acf6ee5f2ad0

**Comment by RuthlessRuler** [comment] 2024-10-15 15:38
Completely breaks for me for links that dont have preferred browser.

https://github.com/user-attachments/assets/4cc9fbd2-4e42-45a8-8b76-c0e84d1fdfb5

**Comment by 1fexd** [comment] 2024-10-15 15:52
Just pushed a fix, building right now

**Comment by RuthlessRuler** [comment] 2024-10-15 20:32
Works now. Thanks alot for such quick fixes!

**Closed** 2024-10-15 20:33 UTC
Labels: t/needs-feedback, t/bug
